stages:
  - build
  - test

cache:
  paths:
    - ~/.gradle/caches

before_script:
  - apk add --update ca-certificates  # Optional, ensures certificate validation for downloading dependencies

build:
  stage: build
  script:
    - docker pull adoptium/temurin:17-jre  # Download Oracle OpenJDK 17 image
    - docker run --rm adoptium/temurin:17-jre gradle clean
    - docker run --rm adoptium/temurin:17-jre gradle build

test:
  stage: test
  script:
    - docker pull adoptium/temurin:17-jre  # Download Oracle OpenJDK 17 image
    - docker run --rm adoptium/temurin:17-jre gradle test