stages:
  - build
  - test

cache:
  paths:
    - ~/.gradle/caches

before_script:
  - gradle clean

build:
  stage: build
  script:
    - docker pull adoptium/temurin:21-jre  # Download Oracle OpenJDK 21 image (without compiler)
    - docker run --rm adoptium/temurin:21-jre gradle build

test:
  stage: test
  script:
    - docker pull adoptium/temurin:21-jre  # Download Oracle OpenJDK 21 image (without compiler)
    - docker run --rm adoptium/temurin:21-jre gradle test