image: openjdk:21-slim  # Use OpenJDK 21 for compatibility

stages:
  - build
  - deploy

build:
  stage: build
  script: ./gradlew build  # Assuming Gradle wrapper is present
  artifacts:
    paths:
      - build/libs/*.jar      # Adjust path based on your Gradle project structure
