stages:
  - build
  - test

cache:
  paths:
    - ~/.gradle/caches

before_script:
  - apk add --update ca-certificates  # Optional, ensures certificate validation for downloading dependencies

build:
  stage: build
  script:
    - docker pull eclipse-temurin:21-jdk
    - docker run --rm eclipse-temurin:21-j gradle clean
    - docker run --rm eclipse-temurin:21-j gradle build

test:
  stage: test
  script:
    - docker pull eclipse-temurin:21-j
    - docker run --rm eclipse-temurin:21-j gradle test
