image: jdk:21

stages:
 ## - build
 ## - test
 ## - deploy

cache:
  paths:
    - ~/.gradle/caches

before_script:
  - gradle clean

build:
  stage: build
  script:
  - gradle build

test:
  stage: test
  script:
  - gradle test

##deploy:
##  stage: deploy
##  script: echo "Define your deployment script!"
##  environment: production
