image: jdk:21

stages:
  - build
  - test  # Uncommented test stage

cache:
  paths:
    - ~/.gradle/caches

before_script:
  - gradle clean

build:
  stage: build
  script:
    - gradle build

test:
  stage: test
  script:
    - gradle test