pebble:
    suffix: .peb
    cache: false
    exposeRequestAttributes: true
    prefix: templates/

spring:
    datasource:
        # store data in a persistent file, mode MySQL and enable server
        url: jdbc:h2:file:./data/application;MODE=MySQL;AUTO_SERVER=true;
    sql:
        init:
            mode: always
    h2:
        console:
            enabled: true
    jpa:
        defer-datasource-initialization: true
        show-sql: true
        hibernate:
            ddl-auto: update
    security:
      # for development purposes
      user:
        name: admin
        password: admin

